const heroPhrases = [
  "Transforma tu {cuerpo}, fortalece tu {mente}.",
  "Supera tus {límites} cada día.",
  "Construye tu {versión} más fuerte.",
  "El {dolor} es temporal, el orgullo es {eterno}.",
  "Despierta tu {potencial} oculto.",
  "Forja tu {carácter} con cada repetición.",
  "No busques {excusas}, encuentra {resultados}.",
  "Tu única {competencia} eres tú mismo.",
  "El {sacrificio} de hoy es tu {triunfo} de mañana.",
  "Entrena como si {dependiera} de ti.",
  "Cada {gota} de sudor te acerca a tu {meta}.",
  "La {disciplina} vence a la motivación.",
  "No es {suerte}, es {trabajo} duro.",
  "Tu {cuerpo} escucha todo lo que tu mente {dice}.",
  "El {cambio} comienza cuando tú {decides}.",
  "Haz que cada {serie} cuente.",
  "La {fuerza} no viene de ganar, viene de la {lucha}.",
  "Rompé tus {barreras}, construye tu {legado}.",
  "El {gimnasio} es tu santuario, entrena con {respeto}.",
  "No te rindas, el {progreso} es silencioso.",
  "Tu {mentalidad} define tus {resultados}.",
  "El mejor {momento} para empezar es {ahora}.",
  "Conviértete en la {mejor} versión de ti.",
  "La {constancia} es más importante que la {intensidad}.",
  "Cada {día} es una oportunidad para {mejorar}.",
  "El {éxito} es la suma de pequeños {esfuerzos}.",
  "Tu {actitud} determina tu {altitud}.",
  "No cuentes los {días}, haz que los días {cuenten}.",
  "La {excelencia} no es un acto, es un {hábito}.",
  "El {límite} es solo el comienzo.",
  "Sé más fuerte que tu {mejor} excusa.",
  "La {transformación} empieza en tu {interior}.",
  "El {hierro} no miente, el {espejo} tampoco.",
  "Cada {repetición} es una victoria.",
  "La {pasión} mueve montañas.",
  "Tu {esfuerzo} de hoy define tu mañana.",
  "El {dolor} que sientes hoy es la {fuerza} que tendrás mañana.",
  "No esperes el momento {perfecto}, crea tu {momento}.",
  "La {consistencia} construye campeones.",
  "Tu {cuerpo} es tu templo, {cuídalo}.",
  "El {sudor} es la tinta con la que escribes tu {historia}.",
  "No te compares con {nadie}, compite contra tu {ayer}.",
  "Cada {paso} cuenta en el camino hacia tu {meta}.",
  "La {voluntad} es tu músculo más {fuerte}.",
  "El {entrenamiento} es medicina para el {alma}.",
  "Despierta con {determinación}, duerme con {satisfacción}.",
  "Tu {futuro} se construye en el presente.",
  "No hay {atajos} para llegar a la {cima}.",
  "La {disciplina} es el puente entre {metas} y logros.",
  "El {poder} está en tu {interior}.",
  "Cada {mañana} es una nueva oportunidad para {brillar}.",
  "La {resistencia} se forja en los días {difíciles}.",
  "Tu {compromiso} es tu superpoder.",
  "El {cambio} real requiere {acción}.",
  "No subestimes tu {capacidad} de {superación}.",
  "La {grandeza} no se regala, se {construye}.",
  "El {gimnasio} es donde los {sueños} se convierten en músculo.",
  "Tu {sonrisa} después del entreno lo dice {todo}.",
  "La {victoria} más importante es sobre ti {mismo}.",
  "Cada {repetición} escribe tu {leyenda}.",
  "El {descanso} también es parte del {progreso}.",
  "Tu {cuerpo} puede soportar casi {cualquier} cosa.",
  "La {mente} es el límite, no el {cuerpo}.",
  "El {fuego} interior debe ser más grande que el de {afuera}.",
  "No dejes que el {miedo} decida tu {futuro}.",
  "La {persistencia} rompe todas las {barreras}.",
  "Tu {esfuerzo} silencioso se convertirá en {ruido}.",
  "El {ahora} es el único momento que {importa}.",
  "Cada {caída} es una lección disfrazada.",
  "La {fortaleza} nace en la {adversidad}.",
  "Tu {entreno} es tu ritual sagrado.",
  "El {progreso} no es lineal, pero siempre {avanza}.",
  "La {confianza} se gana en el {esfuerzo} diario.",
  "No hay {gloria} sin {sacrificio}.",
  "Tu {cuerpo} cambia cuando tu {mente} cambia primero.",
  "El {éxito} es la suma de hábitos {diarios}.",
  "Cada {día} sin entrenar es un día {perdido}.",
  "La {mejor} inversión es en ti {mismo}.",
  "El {dolor} del entrenamiento es {temporal}.",
  "Tu {legado} se escribe con cada {repetición}.",
  "La {disciplina} es hacer lo que {duele}.",
  "No esperes {resultados} diferentes haciendo lo {mismo}.",
  "El {poder} personal se cultiva en el {esfuerzo}.",
  "Tu {cuerpo} es la única casa que tienes, {cuídala}.",
  "Cada {sesión} es un escalón hacia tu {mejor} versión.",
  "La {superación} personal es un viaje, no un {destino}.",
  "El {hierro} no juzga, solo {transforma}.",
  "Tu {determinación} es más fuerte que cualquier {obstáculo}.",
  "La {pasión} por entrenar nunca se {apaga}.",
  "El {mañana} agradecerá el esfuerzo de {hoy}.",
  "No busques {motivación}, construye {disciplina}.",
  "Tu {sudor} es la prueba de tu {dedicación}.",
  "El {cambio} que quieres ver empieza en tu {interior}.",
  "La {exigencia} personal te lleva a la {excelencia}.",
  "Cada {respiración} es una oportunidad para {renovarte}.",
  "La {fortaleza} mental se forja con {repetición}.",
  "Tu {cuerpo} es tu obra de arte, {esculpelo}.",
  "El {éxito} no es casualidad, es {trabajo}.",
  "La {consistencia} vence al {talento}.",
  "No hay {límites} cuando hay {voluntad}.",
  "Tu {mejor} versión te está esperando.",
  "El {sacrificio} de hoy es la {libertad} de mañana.",
  "La {transformación} es un acto de {valentía}.",
  "Cada {gota} de sudor acerca tu {sueño}.",
];
